//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public Addresses()
        {
            this.Transactions = new HashSet<Transactions>();
            this.Users1 = new HashSet<Users1>();
        }
    
        public int Id { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<int> Instance_Id { get; set; }
    
        public virtual Instance Instance { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
        public virtual ICollection<Users1> Users1 { get; set; }

        /// <summary>
        /// Current balance of points that this address has to spend.
        /// </summary>
        public virtual long Points
        {
            get { return Transactions == null ? 0 : Transactions.Sum(t => t.Points); }
        }

    }
}
