//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItems
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public System.Guid User_Id { get; set; }
        public int Reward_Id { get; set; }
    
        public virtual Rewards Rewards { get; set; }
        public virtual Users1 Users1 { get; set; }


        /// <summary>
        /// Total cost of this item. That is, the reward price times the number of it.
        /// </summary>
        public long Cost
        {
            get { return Rewards.Price * Quantity; }
        }



        public decimal DollarCost
        {
            get { return Rewards.DollarPrice * Quantity; }
        }
    }
}
