//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class greenMoneyEntities : DbContext
    {
        public greenMoneyEntities()
            : base("name=greenMoneyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Applications> Applications { get; set; }
        public DbSet<Memberships> Memberships { get; set; }
        public DbSet<Profiles> Profiles { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Addresses> Addresses { get; set; }
        public DbSet<CartItems> CartItems { get; set; }
        public DbSet<CMS> CMS { get; set; }
        public DbSet<Instance> Instance { get; set; }
        public DbSet<InterestedPeople> InterestedPeople { get; set; }
        public DbSet<InvitedNeighbours> InvitedNeighbours { get; set; }
        public DbSet<InvitedUsers> InvitedUsers { get; set; }
        public DbSet<LoginToken> LoginToken { get; set; }
        public DbSet<Pages> Pages { get; set; }
        public DbSet<Resources> Resources { get; set; }
        public DbSet<ResourceTypes> ResourceTypes { get; set; }
        public DbSet<RewardCategories> RewardCategories { get; set; }
        public DbSet<Rewards> Rewards { get; set; }
        public DbSet<Sections> Sections { get; set; }
        public DbSet<Transactions> Transactions { get; set; }
        public DbSet<Uploads> Uploads { get; set; }
        public DbSet<Users1> Users1 { get; set; }
        public DbSet<UserToken> UserToken { get; set; }
        public DbSet<Vouchers> Vouchers { get; set; }
        public DbSet<AwardPointsOptions> AwardPointsOptions { get; set; }
        public DbSet<ChallengeCategories> ChallengeCategories { get; set; }
        public DbSet<Challenges> Challenges { get; set; }
        public DbSet<LocationOptions> LocationOptions { get; set; }
        public DbSet<ParticipationFrequency> ParticipationFrequency { get; set; }
        public DbSet<UserChallenges> UserChallenges { get; set; }
    }
}
