//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instance
    {
        public Instance()
        {
            this.Addresses = new HashSet<Addresses>();
            this.Rewards = new HashSet<Rewards>();
            this.Users1 = new HashSet<Users1>();
            this.Challenges = new HashSet<Challenges>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Url { get; set; }
        public int order { get; set; }
        public string postcodes { get; set; }
        public string Photo { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> LogoImageId { get; set; }
    
        public virtual ICollection<Addresses> Addresses { get; set; }
        public virtual ICollection<Rewards> Rewards { get; set; }
        public virtual ICollection<Users1> Users1 { get; set; }
        public virtual ICollection<Challenges> Challenges { get; set; }
    }
}
