//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestedPeople
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public bool FreeStandingHome { get; set; }
        public Nullable<bool> HasRfidTag { get; set; }
        public bool SendEmailOffers { get; set; }
        public bool SendEmailUpdates { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    }
}
