//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rewards
    {
        public Rewards()
        {
            this.CartItems = new HashSet<CartItems>();
            this.Vouchers = new HashSet<Vouchers>();
        }
    
        public int Id { get; set; }
        public bool Display { get; set; }
        public Nullable<System.DateTime> AvailableFrom { get; set; }
        public Nullable<System.DateTime> AvailableTo { get; set; }
        public int CategoryId { get; set; }
        public string PartnerName { get; set; }
        public string PartnerLocation { get; set; }
        public string PartnerHours { get; set; }
        public string PartnerPhone { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerUrl { get; set; }
        public string PartnerDescription { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Price { get; set; }
        public string TermsAndConditions { get; set; }
        public string Faq { get; set; }
        public string HowToRedeem { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public int Popularity { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<int> ImageSmallId { get; set; }
        public Nullable<int> VoucherBarcodeId { get; set; }
        public Nullable<int> ImageHomeId { get; set; }
        public decimal DollarPrice { get; set; }
        public bool M { get; set; }
        public bool NotifyOnRedeem { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.Guid> Owner_Id { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<bool> Mobile { get; set; }
        public string Instructions { get; set; }
        public int Instance_Id { get; set; }
        public Nullable<int> Image1Id { get; set; }
        public Nullable<int> Image2Id { get; set; }
        public Nullable<int> Image3Id { get; set; }
        public Nullable<int> Image4Id { get; set; }
    
        public virtual ICollection<CartItems> CartItems { get; set; }
        public virtual Instance Instance { get; set; }
        public virtual RewardCategories RewardCategories { get; set; }
        public virtual Uploads Uploads { get; set; }
        public virtual Uploads Uploads1 { get; set; }
        public virtual Uploads Uploads2 { get; set; }
        public virtual Uploads Uploads3 { get; set; }
        public virtual Users1 Users1 { get; set; }
        public virtual ICollection<Vouchers> Vouchers { get; set; }
    }
}
