//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardCategories
    {
        public RewardCategories()
        {
            this.Rewards = new HashSet<Rewards>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Photo { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual ICollection<Rewards> Rewards { get; set; }
    }
}
