//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sections
    {
        public Sections()
        {
            this.Pages = new HashSet<Pages>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string URLValue { get; set; }
        public bool Hidden { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Instance_Id { get; set; }
    
        public virtual ICollection<Pages> Pages { get; set; }
    }
}
