//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public string Description { get; set; }
        public long Points { get; set; }
        public int Address_Id { get; set; }
        public Nullable<System.Guid> User_Id { get; set; }
        public Nullable<int> TransactionTypeID { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual Users1 Users1 { get; set; }
    }
}
