//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uploads
    {
        public Uploads()
        {
            this.Rewards = new HashSet<Rewards>();
            this.Rewards1 = new HashSet<Rewards>();
            this.Rewards2 = new HashSet<Rewards>();
            this.Rewards3 = new HashSet<Rewards>();
            this.Users11 = new HashSet<Users1>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public byte[] Contents { get; set; }
        public Nullable<System.Guid> UploadedBy_Id { get; set; }
    
        public virtual ICollection<Rewards> Rewards { get; set; }
        public virtual ICollection<Rewards> Rewards1 { get; set; }
        public virtual ICollection<Rewards> Rewards2 { get; set; }
        public virtual ICollection<Rewards> Rewards3 { get; set; }
        public virtual Users1 Users1 { get; set; }
        public virtual ICollection<Users1> Users11 { get; set; }
    }
}
