//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        public System.Guid Id { get; set; }
        public System.DateTime Issued { get; set; }
        public int Reward_Id { get; set; }
        public System.Guid User_Id { get; set; }
    
        public virtual Rewards Rewards { get; set; }
        public virtual Users1 Users1 { get; set; }
    }
}
